version: '3'

services:
  api:
    build:
      context: .
      dockerfile: "./docker/golang/Dockerfile"
    ports:
      - "80:80"
    container_name: api
    depends_on:
      - mysql
    volumes:
      - ./api/:/go/src/github.com/hiromu-saito/cafe-quest/api
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: cafe-quest
      MYSQL_HOST: mysql
    tty: true

  front:
    build:
      context: .
      dockerfile: "./docker/vue/Dockerfile"
    volumes:
      - ./front:/src/front
    ports:
      - "8080:8080"
    container_name: front
    tty: true

  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: cafe-quest
    ports:
      - "3306:3306"
    container_name: mysql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf